<?php declare(strict_types=1);

namespace Contena\Core\Content\Flow\Dispatching;

use Doctrine\DBAL\Connection;
use Psr\Log\LoggerInterface;
use Contena\Core\Framework\Context;
use Contena\Core\Framework\DataAbstractionLayer\Doctrine\FetchModeHelper;
use Contena\Core\Framework\Uuid\Uuid;

/**
 * @internal not intended for decoration or replacement
 *
 * @phpstan-import-type EventGroupedFlowHolders from AbstractFlowLoader
 */
class FlowLoader extends AbstractFlowLoader
{
    public function __construct(
        private readonly Connection $connection,
        private readonly LoggerInterface $logger
    ) {
    }

    public function load(Context $context): array
    {
        $tenantCondition = '';
        $parameters = [];
        if (!$context->hasGlobalTenantAccess()) {
            $tenantCondition = $context->getTenantId() === null
                ? ' AND `tenant_id` IS NULL'
                : ' AND `tenant_id` = :tenantId';

            if ($context->getTenantId() !== null) {
                $parameters['tenantId'] = Uuid::fromHexToBytes($context->getTenantId());
            }
        }

        $flows = $this->connection->fetchAllAssociative(
            'SELECT `event_name`, LOWER(HEX(`id`)) as `id`, `name`, `payload` FROM `flow`
                WHERE `active` = 1 AND `invalid` = 0 AND `payload` IS NOT NULL
                ' . $tenantCondition . '
                ORDER BY `priority` DESC',
            $parameters,
        );

        if ($flows === []) {
            return [];
        }

        foreach ($flows as $key => $flow) {
            try {
                /** @phpstan-ignore contena.unserializeUsage (payload is generated by FlowPayloadUpdater) */
                $payload = \unserialize($flow['payload']);
            } catch (\Throwable $e) {
                $this->logger->error(
                    "Flow payload is invalid:\n"
                    . 'Flow name: ' . $flow['name'] . "\n"
                    . 'Flow id: ' . $flow['id'] . "\n"
                    . $e->getMessage() . "\n"
                    . 'Error Code: ' . $e->getCode() . "\n"
                );

                continue;
            }

            $flows[$key]['payload'] = $payload;
        }

        $result = FetchModeHelper::group($flows);

        /** @var EventGroupedFlowHolders $result */
        // @phpstan-ignore varTag.type (with the FetchModeHelper we lose the payload type information)
        return $result;
    }
}
